services:
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto
    user: "1000:1000" # get via id -u and id -g for user and group in linux
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    restart: unless-stopped

